// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGTpjQiQfySgS6hfqHcvrhAbGh0Xq-9PA',
    appId: '1:392171194091:web:11c839460e6f38d02be0ae',
    messagingSenderId: '392171194091',
    projectId: 'nutrisync-2def4',
    authDomain: 'nutrisync-2def4.firebaseapp.com',
    storageBucket: 'nutrisync-2def4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfvlfkI_sEAsSNBJLZJfOVg2hqr_Pqz28',
    appId: '1:392171194091:android:86bb87e298027a8f2be0ae',
    messagingSenderId: '392171194091',
    projectId: 'nutrisync-2def4',
    storageBucket: 'nutrisync-2def4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClvPo5n9QUywDusvHsI4exwiivFz_7KTU',
    appId: '1:392171194091:ios:57a10a34a25ea3712be0ae',
    messagingSenderId: '392171194091',
    projectId: 'nutrisync-2def4',
    storageBucket: 'nutrisync-2def4.firebasestorage.app',
    iosBundleId: 'com.example.nutriSync',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClvPo5n9QUywDusvHsI4exwiivFz_7KTU',
    appId: '1:392171194091:ios:57a10a34a25ea3712be0ae',
    messagingSenderId: '392171194091',
    projectId: 'nutrisync-2def4',
    storageBucket: 'nutrisync-2def4.firebasestorage.app',
    iosBundleId: 'com.example.nutriSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGTpjQiQfySgS6hfqHcvrhAbGh0Xq-9PA',
    appId: '1:392171194091:web:2f4b188ee59029d72be0ae',
    messagingSenderId: '392171194091',
    projectId: 'nutrisync-2def4',
    authDomain: 'nutrisync-2def4.firebaseapp.com',
    storageBucket: 'nutrisync-2def4.firebasestorage.app',
  );
}
